CREATE TABLE IF NOT EXISTS "public"."user" (
	"id" int GENERATED BY DEFAULT AS IDENTITY,
  "uid" UUID DEFAULT uuid_generate_v4(),
  "email" text UNIQUE NOT NULL,
	"name" varchar(256),
	"phone" varchar(256),
	"password" text NOT NULL,
	"role" text NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "email_verified_at" TIMESTAMPTZ NULL,

  CONSTRAINT "pk__user" PRIMARY KEY ("id"),
  CONSTRAINT "ux__user__email" UNIQUE("email")
);

CREATE TRIGGER user__upd_before__updated_at_timestamp
BEFORE UPDATE ON "public"."user"
FOR EACH ROW EXECUTE PROCEDURE trigger_set_timestamp();
